build_test_shared_unix:
  type: build
  tags:
    - unix
  script:
    - git remote set-url origin ${CI_BUILD_REPO}
    - git submodule update --init --recursive -- cmake
    - git submodule update --init --recursive -- ci_script/hslib_ci_script
    - ${CI_PROJECT_DIR}/ci_script/${CI_PROJECT_NAME}_cmake_generate.sh --build_shared --build_type "Release" "Unix Makefiles"
    - ${CI_PROJECT_DIR}/ci_script/${CI_PROJECT_NAME}_install.sh --build_shared --build_type "Release" "Unix Makefiles"
    - ${CI_PROJECT_DIR}/ci_script/${CI_PROJECT_NAME}_build_test.sh --build_shared --build_type "Release" "Unix Makefiles"

run_test_shared_unix:
  type: test
  tags:
    - unix
  script:
    - ${CI_PROJECT_DIR}/ci_script/${CI_PROJECT_NAME}_run_test.sh --build_shared --build_type "Release" "Unix Makefiles"

build_test_shared_windows:
  type: build
  tags:
    - windows
  script:
    - git remote set-url origin ${CI_BUILD_REPO}
    - git submodule update --init --recursive -- cmake
    - git submodule update --init --recursive -- ci_script/hslib_ci_script
    - ${CI_PROJECT_DIR}/ci_script/${CI_PROJECT_NAME}_cmake_generate.sh --build_shared "Visual Studio 12 Win64"
    - ${CI_PROJECT_DIR}/ci_script/${CI_PROJECT_NAME}_install.sh --build_shared "Visual Studio 12 Win64"
    - ${CI_PROJECT_DIR}/ci_script/${CI_PROJECT_NAME}_build_test.sh --build_shared "Visual Studio 12 Win64"

run_test_shared_windows:
  type: test
  tags:
    - windows
  script:
    - ${CI_PROJECT_DIR}/ci_script/${CI_PROJECT_NAME}_run_test.sh --build_shared "Visual Studio 12 Win64"

build_test_static_unix:
  type: build
  tags:
    - unix
  script:
    - git remote set-url origin ${CI_BUILD_REPO}
    - git submodule update --init --recursive -- cmake
    - git submodule update --init --recursive -- ci_script/hslib_ci_script
    - ${CI_PROJECT_DIR}/ci_script/${CI_PROJECT_NAME}_cmake_generate.sh --build_type "Release" "Unix Makefiles"
    - ${CI_PROJECT_DIR}/ci_script/${CI_PROJECT_NAME}_install.sh --build_type "Release" "Unix Makefiles"
    - ${CI_PROJECT_DIR}/ci_script/${CI_PROJECT_NAME}_build_test.sh --build_type "Release" "Unix Makefiles"

run_test_static_unix:
  type: test
  tags:
    - unix
  script:
    - ${CI_PROJECT_DIR}/ci_script/${CI_PROJECT_NAME}_run_test.sh --build_type "Release" "Unix Makefiles"

build_test_static_windows:
  type: build
  tags:
    - windows
  script:
    - git remote set-url origin ${CI_BUILD_REPO}
    - git submodule update --init --recursive -- cmake
    - git submodule update --init --recursive -- ci_script/hslib_ci_script
    - ${CI_PROJECT_DIR}/ci_script/${CI_PROJECT_NAME}_cmake_generate.sh "Visual Studio 12 Win64"
    - ${CI_PROJECT_DIR}/ci_script/${CI_PROJECT_NAME}_install.sh "Visual Studio 12 Win64"
    - ${CI_PROJECT_DIR}/ci_script/${CI_PROJECT_NAME}_build_test.sh "Visual Studio 12 Win64"

run_test_static_windows:
  type: test
  tags:
    - windows
  script:
    - ${CI_PROJECT_DIR}/ci_script/${CI_PROJECT_NAME}_run_test.sh "Visual Studio 12 Win64"
